[package]
name = "foch-engine"
version.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
blake3 = "1.5.5"
bincode.workspace = true
rkyv.workspace = true
dirs.workspace = true
flate2.workspace = true
globset.workspace = true
foch = { path = "../.." }
foch-cwt = { path = "../foch-cwt" }
foch-language = { path = "../foch-language" }
foch-merge-kernel = { path = "../foch-merge-kernel" }
rayon.workspace = true
reqwest.workspace = true
remove_dir_all.workspace = true
rustix.workspace = true
same-file.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tempfile.workspace = true
toml.workspace = true
toml_edit = "0.23"
tracing.workspace = true
walkdir.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
windows-sys.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
libc = "0.2.186"

[dev-dependencies]
filetime = "0.2"
foch = { path = "../..", features = ["test-utils"] }
