[package]
name = "foch-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
arbitrary = { version = "1.4", features = ["derive"] }
foch = { path = ".." }
libfuzzer-sys = "0.4"

[workspace]
members = ["."]

[[bin]]
name = "property_clausewitz_parser"
path = "fuzz_targets/property_clausewitz_parser.rs"
test = false
doc = false
bench = false

[[bin]]
name = "property_decode_paradox_bytes"
path = "fuzz_targets/property_decode_paradox_bytes.rs"
test = false
doc = false
bench = false
